# Generated by Django 4.2.7 on 2023-12-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0003_remove_post_imagepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
